trigger:
  branches:
    include:
    - main
variables:
- name: azureSubscription
  value: '2041b05f-4689-4287-82fb-9dea409345ac'
- name: webAppName
  value: 'webgoat_test'
- name: environmentName
  value: 'test_env'
- name: vmImageName
  value: 'ubuntu-latest'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      name: 'Default'
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '6.x'
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'snyk_api'
        testType: 'app'
        monitorWhen: 'always'
        failOnIssues: true
        projectName: 'test_project'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@0
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: drop

