trigger:
- main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Service connection for Snyk
  snykServiceConnection: 'snyk_api'  # Update this with your actual Snyk service connection name

  # Project name for Snyk
  snykProjectName: 'test_project'  # Update this with your actual project name in Snyk

stages:
- stage: CodeSecurityScan
  displayName: Snyk Code Security Scan
  jobs:
  - job: SnykScan
    displayName: Snyk Security Scan
    pool:
      name: 'AWESELSKI-N'  # Replace with your agent pool name

    steps:
    - checkout: self

    - task: SnykSecurityScan@1
      displayName: 'Perform Snyk Security Scan'
      inputs:
        serviceConnectionEndpoint: $(snykServiceConnection)
        testType: 'app'
        monitorWhen: 'always'
        failOnIssues: true
        projectName: $(snykProjectName)
