# Maven package Java project Web App to Linux on Azure


trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '2041b05f-4689-4287-82fb-9dea409345ac'

  # Web app name
  webAppName: 'webgoat_test'

  # Environment name
  environmentName: 'test_env'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Service connection for Snyk
  snykServiceConnection: 'snyk_api'  # Update this with your actual Snyk service connection name

  # Project name for Snyk
  snykProjectName: 'test_project'  # Update this with your actual project name in Snyk

stages:
- stage: CodeSecurityScan
  displayName: Snyk Code Security Scan
  jobs:
  - job: SnykScan
    displayName: Snyk Security Scan
    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self

    - task: SnykSecurityScan@1
      displayName: 'Perform Snyk Security Scan'
      inputs:
        serviceConnectionEndpoint: $(snykServiceConnection)
        testType: 'app'
        monitorWhen: 'always'
        failOnIssues: true
        projectName: $(snykProjectName)


